# Generated by Django 6.0.4 on 2026-04-19 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CANCEL_EVENT', 'Cancel Event'), ('POSTPONE_EVENT', 'Postpone Event'), ('PUBLISH_EVENT', 'Publish Event'), ('CLOSE_EVENT', 'Close Event'), ('SEND_ADDRESS', 'Send Address'), ('MANUAL_ADDRESS_REVEAL', 'Manual Address Reveal')], max_length=50)),
                ('target', models.CharField(help_text='ID of the affected entity', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='dashboard.adminuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
