# Generated by Django 6.0.4 on 2026-04-19 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('zone', models.CharField(help_text='Public location zone e.g. Lekki', max_length=100)),
                ('full_address', models.TextField(help_text='Private — never expose publicly')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='DRAFT', max_length=20)),
                ('address_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_event', models.ForeignKey(blank=True, help_text='Next event for cancellation transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_events', to='events.event')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Regular, VIP', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inclusions', models.TextField(help_text='e.g. Entry + 2 Martell')),
                ('total_slots', models.PositiveIntegerField()),
                ('reserved_slots', models.PositiveIntegerField(default=0)),
                ('confirmed_slots', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='events.event')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
