# Generated by Django 6.0.4 on 2026-04-19 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('TRANSFERRED', 'Transferred'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('address_sent', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.tickettier')),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_registrations', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
